services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install && npm run build
      php artisan migrate --force
    startCommand: |
      vendor/bin/heroku-php-apache2 public/